version: "3.8"
services:
  breeze:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: breeze
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - /var/www/breeze/data:/app/data
    networks:
      - joeburgess-network

networks:
  joeburgess-network:
    name: joeburgess-network
    external: true
