version: "3"

services:
  breeze-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=/app/data/gust.db
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    networks:
      - breeze-network

networks:
  breeze-network:
    driver: bridge
