version: "3.8"

services:
  breeze:
    image: ghcr.io/josephburgess/breeze:latest
    container_name: breeze
    restart: unless-stopped
    env_file:
      - /var/www/breeze/.env
    ports:
      - "8080:8080"
    volumes:
      - /var/www/breeze/data:/app/data
