version: "3"

services:
  breeze-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/gust.db
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    networks:
      - breeze-network

networks:
  breeze-network:
    driver: bridge
